[package]
name = "fasta_windows"
version = "0.2.1"
authors = ["Max Brown <mb39@sanger.ac.uk>"]
edition = "2018"

[dependencies]
bio = "*"
clap = "~2.27.0"
rayon = "1.5.0"
indicatif = "*"
itertools = "0.10.1"