[package]
name = "fasta_windows"
version = "0.2.0"
authors = ["Max Brown <mb39@sanger.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "*"
clap = "~2.27.0"
rayon = "1.5.0"